// 15. micro-frontend-app/packages/vue-remote/src/App.vue
<template>
  <div class="vue-app">
    <h2>Vue Remote Application</h2>
    <p>This component is rendered by Vue 3.</p>
    <button @click="count++">Count: {{ count }}</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  setup() {
    const count = ref(0);
    return { count };
  },
});
</script>

<style scoped>
.vue-app {
  border: 1px solid green;
  padding: 20px;
  margin: 10px;
}
</style>

// 15. micro-frontend-app/packages/react-host/src/App.tsx
import { useEffect, useRef } from 'react';

import { mount } from 'vueRemote/App';

const VueRemoteWrapper = () => {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (ref.current) {
      mount(ref.current);
    }
  }, []);

  return <div ref={ref} />;
};

const App = () => {
  return (
    <div style={{ border: '1px solid blue', padding: '20px' }}>
      <h1>React Host Application</h1>
      <p>This is a React application hosting a Vue remote.</p>
      <div
        style={{ border: '1px solid red', padding: '20px', marginTop: '20px' }}
      >
        <VueRemoteWrapper />
      </div>
    </div>
  );
};

export default App;
